### ISSUE TITLE
ls parameter isn't POSIX

### ISSUE THREAD

**Issue by leo-arch** [amarakon/dfm#2]
Hi @amarakon. Since the shebang is `/bin/sh` I assume you want this script to be POSIX compliant. However, POSIX `ls` has no `--group-directories-first` option. See **ls**(1p).

As is, `dfm` will run neither on BSD nor MacOS.

**Comment by amarz45** [comment]
I chose `/bin/sh` mainly because I do not have any Bashisms in my script. But I also want the script to be POSIX-compliant, so thanks for letting me now. I am working on a solution that will work on BSD and macOS.

**Comment by amarz45** [comment]
It is fixed on the latest commit but I accidentally messed up the commit message lol. Anyways, it uses `--group-directories-first` if the ls version is GNU coreutils. Otherwise, it will use another command that will work on BSD and macOS.
