### ISSUE TITLE
Option to Open DFM With the Path it Was Previously Run

### ISSUE THREAD

**Issue by cavalo-mORTO** [amarakon/dfm#3]
Hi, could you add an option open dfm on the path it was in the previous run?

**Comment by amarz45** [comment]
For clarification, do you mean the path where you last were before closing the program or the path that the program started with?

**Comment by cavalo-mORTO** [comment]
The path where it was before closing or quitting the program.

**Comment by amarz45** [comment]
Now you can pass the `-r` or `--restore` option to do this. You need to run the program for a second time after this update in order for the cache to take effect.

**Comment by cavalo-mORTO** [comment]
There's an issue. If I open a file, in the next run it'll try to open in the path of the file and fail to do so.
In this case it should keep the path of the directory that contains the file.

**Comment by cavalo-mORTO** [comment]
I have a patch here: https://api.pastecode.io/anon/raw-snippet/j5mvzgmj?raw=inline&ticket=d12e6881-b1c1-4e41-9938-c6b70b45bf05

**Comment by amarz45** [comment]
I tested your patch and it fixes the issue. Can you please open a pull request with the change you made?

**Comment by cavalo-mORTO** [comment]
Done.
